- name: Install required packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

- name: Add docker apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker apt repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update apt
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install docker
  apt:
    name: "{{ packages }}"
    update_cache: true
    state: present
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Add user to the docker group
  user:
    name: ubuntu
    groups: docker
    append: yes

- name: Install docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: 0755